version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: interview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: interview
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile

    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
