FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*


COPY backend/ ./

COPY backend/requirements.txt ./

COPY backend/entrypoint.sh ./

# Copy the Python dependencies file and install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Make the entrypoint script executable
RUN chmod +x entrypoint.sh

# Expose port
EXPOSE 8000

# Use the entrypoint script to run migrations and start the server
ENTRYPOINT ["/app/entrypoint.sh"]
