# Generated by Django 5.0.7 on 2024-07-22 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
